version: '3'
services:
        postgres:
            build:
                context: .
                dockerfile: Dockerfile-PostgreSQL
            volumes:
                - data_volume:/var/lib/postgresql/data
            environment:
                - POSTGRES_USER=pidsvc-admin
                - POSTGRES_DB=pidsvc
                - POSTGRES_PASSWORD=apassword
        pidsvcMaster:
            build:
                context: .
                dockerfile: Dockerfile-pidsvcMaster
            depends_on:
                - postgres
            expose:
                - "8080"
                - "8009"
        apache:
            build:
                context: .
                dockerfile: Dockerfile-Apache
            depends_on:
                - tomcat3
            ports:
                - "8095:80"
volumes:
    data_volume:
