name: make thing
on:
  push:
    paths:
      - '**.csv'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: get all changed files
      id: files
      uses: jitterbit/get-changed-files@v1
      with:
        token: ${{ github.token }}
      
    - name: post the files
      id: post
      uses: docker://internetofwater/post-geoconnex:latest

      with:
         shell: bash
         args: |
          echo "Do something with this ${{ steps.files.outputs.added_modified }}."
