name: Upload CSV

on:
  repository_dispatch:
    types: [upload-csv]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload CSV
      run: |
        mkdir -p ${{ github.event.client_payload.namespace }}
        echo "${{ github.event.client_payload.content }}" | base64 --decode > "${{ github.event.client_payload.namespace }}/${{ github.event.client_payload.filename }}"
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ${{ github.event.client_payload.namespace }}/${{ github.event.client_payload.filename }}
        git commit -m "Add CSV file to ${{ github.event.client_payload.namespace }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
